### ISSUE TITLE
Error while using yml file

### ISSUE THREAD

**Issue by solaris7x** [maxisoft/Freenom-dns-updater#10]
Heya , I installed fdu using pip 
To install pip I used apt-get install python-pip
Normal fdu command is able to update my domain but not able to update through yml file
[ssh_log_20170812133244.txt](https://github.com/maxisoft/Freenom-dns-updater/files/1219599/leecher.blacky.gq_20170812133244.txt)

**Comment by gerrydoro** [comment]
It seems to be a syntax error on your yml file... Did you edited it on Windows?

**Comment by gerrydoro** [comment]
Anyway, I use now this script (in bash)
https://gist.github.com/pgaulon/3a844a626458f56903d88c5bb1463cc6
Because it's lighter, it doesn't needs python and it is also updated with the new Freenom API
