### ISSUE TITLE
Script has stopped working.

### ISSUE THREAD

**Issue by felmur** [maxisoft/Freenom-dns-updater#14]
Hi, in October 2017 this program has stopped working. I presume that freenom has changed something.

**Comment by xand79** [comment]
Btw, seems like not only this script, but my .sh too. In my case it's because of curl output nothing for https login page, and I'm trying to find why...

**Comment by Guilty-King** [comment]
The login page for freenom has changed to freenom.com/dologin.php

**Comment by shiftout** [comment]
Looks like the call to https://my.freenom.com/dologin.php returns HTTP 403.

**Comment by maxisoft** [comment]
Should be fixed by #23
