### ISSUE TITLE
"Unable to login".. functioned before

### ISSUE THREAD

**Issue by bl4ckOut** [maxisoft/Freenom-dns-updater#4]
Hi,

first of all thanks for your work.
I'm using your tool with a .yaml-config file which I'am starting every 10 minutes with cron.
Since yesterday I always get this error: "Unable to login with the given credential"
But my credentials are to 100 % correct.
I also tryied the manual method via fdu record update and uninstall/install, but no success.

Thanks

**Comment by plokker** [comment]
I have the same issue, it seems that freenom has updated the webpage and something must have changed, i will try to submit a commit next week if i have time.

**Comment by bl4ckOut** [comment]
It now works with your fork plokker, thanks for your work.
Maxisoft seems not to be available anymore considering his online time on github.

TO ALL:
USE PLOKKERS FORK !
