### ISSUE TITLE
Doesn't work - multiple errors

### ISSUE THREAD

**Issue by kuriackovskij** [maxisoft/Freenom-dns-updater#6]
Hi !

I can't make it working. When running with inline config, for instance:
fdu record update myemail@gmail.com myPassword123 mydomain.tk
I get the following output:

_> Traceback (most recent call last):

>   File "fdu.py", line 318, in <module>
>     cli()
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
>     return self.main(_args, *_kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
>     rv = self.invoke(ctx)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
>     return ctx.invoke(self.callback, *_ctx.params)
>   File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
>     return callback(_args, **kwargs)
> TypeError: record_update() takes exactly 8 arguments (7 given)
> _ 

And when running with yml config - it says that credentials are incorrect. However they are correct.

Can you please advise?
Thanks!

**Comment by BlasterJoni** [comment]
Same error here

**Comment by gerrydoro** [comment]
@BlasterJoni I now use this
https://gist.github.com/a-c-t-i-n-i-u-m/bc4b1ff265b277dbf195

**Comment by jurbz** [comment]
Getting the same error, [freenom.com.ddns.sh](https://gist.github.com/a-c-t-i-n-i-u-m/bc4b1ff265b277dbf195) doesn't work for me either. Has Freenom made changes?

**Comment by ronkoren** [comment]
Had the same issue with credentials are incorrect, when using yml config, you can fix it by editing  _freenom_dns_updater/freenom.py_ and changing
`return '<li class="addFunds">' in r.text` 
to be
 `return 'action=addfunds' in r.text`

**Comment by maxisoft** [comment]
Hello, I'm back.
Thanks for your issues and comments.
The 2 issues described here were fixed :
- The first one was fixed with commit 0e3d75695073c04ae2d4cbe9f5f23f09354b0c02
- The last one was fixed via a pull request #5 

To install and use the new 1.1.1 version launch :
``pip install --upgrade freenom-dns-updater``

**Comment by maxisoft** [comment]
Closing this issue.
If something is still wrong comment this issue or reopen another issue.
